@accountId = 100


//create account
###
    POST http://localhost:8070/account 
    content-type: application/json

    {
        "owner": "hossein alizadeh",
        "currency": "USD"
    }

    // validation requierd
###
    POST http://localhost:8070/account 
    content-type: application/json

    {
        "owner": "",
        "currency": ""
    }

// get account

###
    GET http://localhost:8070/account/{{accountId}}

    //  validation not found
###
    GET http://localhost:8070/account/5000

    //  validation min
###
    GET http://localhost:8070/account/-1

// list account
@page_id = 100
@page_size= 5
###
    GET http://localhost:8070/account?page_id={{page_id}}&page_size={{page_size}}